import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="max-w-4xl mx-auto p-4">
                <Header />
          {children}
          <footer className="border-t border-gray-300 p-8 text-center text-gray-600 mt-16 bg-gray-50">
        <p className="text-sm">&copy; 2025 All rights reserved</p>
        <p className="text-sm">Powered by <span className="font-semibold text-yellow-600">Rial</span></p>
      </footer>
        </main>
      </body>
    </html>
  );
}
